# Generated by Django 4.1 on 2022-09-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='decscription',
        ),
        migrations.AddField(
            model_name='todolist',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
